### ISSUE TITLE
No such file or directory '.meteor/release'

### ISSUE THREAD

**Issue by deanrad** [jamesdwilson/meteor-jw-opinionated-skeleton#1]
If you're getting this issue, it's because the cp -r command did not copy over the .meteor folder because it's hidden by default.

manually:
`cp -rf meteor-skeleton/* ~/.meteor/tools/latest/tools/skel/` 
`cp -rf meteor-skeleton/.meteor ~/.meteor/tools/latest/tools/skel/` 

and you'll be good to go.

```


meteor create foo

/Users/dean/.meteor/tools/0663f84bef/tools/meteor.js:1480
}).run();
   ^
Error: ENOENT, no such file or directory 'foo/.meteor/release'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.writeFileSync (fs.js:966:15)
    at Object._.extend.writeMeteorReleaseVersion (/Users/dean/.meteor/tools/0663f84bef/tools/project.js:73:8)
    at Object.Commands.push.func (/Users/dean/.meteor/tools/0663f84bef/tools/meteor.js:529:15)
    at runCommand (/Users/dean/.meteor/tools/0663f84bef/tools/meteor.js:354:17)
    at main (/Users/dean/.meteor/tools/0663f84bef/tools/meteor.js:1476:5)
    at /Users/dean/.meteor/tools/0663f84bef/tools/meteor.js:1479:3
```

**Comment by jamesdwilson** [comment]
Sorry was this an actual bug? Or did you want me to update the docs? Or what is this in response to?
